### ISSUE TITLE
Our neat russian projects

### ISSUE THREAD

**Issue by direvius** [IonicaBizau/made-in-russia#7]
https://github.com/yandex/yandex-tank
https://github.com/yandex/ClickHouse
https://github.com/yandex/pandora

**Comment by IonicaBizau** [comment]
Cool! Feel free to open a pull request and add them! ✨

**Comment by svetlyak40wt** [comment]
This list seem like an auto-generated. Isn't it?

**Comment by IonicaBizau** [comment]
Correct, but you can contribute too.

**Comment by velavokr** [comment]
https://github.com/pyos/re2jit - a jit compiler for re2, adding backrefs and speeding up the unicode matching. C++
https://github.com/pyos/libcno - a neat io-abstract http/2 implementation. C

**Comment by IonicaBizau** [comment]
Amazing, but please open pull requests! 😄

**Comment by IonicaBizau** [comment]
I merged #9. Feel free to open pull requests with new projects! 👍
